export const TRAINER_ACTION_TYPES = {
  GET_CLIENTS_SUCCESS: "trainer/GET_CLIENTS_SUCCESS",
  GET_CLIENTS_FAILED: "trainer/GET_CLIENTS_FAILED",
  GET_CLIENTSLASTVISITED_SUCCESS: "trainer/GET_CLIENTSLASTVISITED_SUCCESS",
  GET_CLIENTSLASTVISITED_FAILED: "trainer/GET_CLIENTSLASTVISITED_FAILED",
  ADD_CLIENT_SUCCESS: "trainer/ADD_CLIENT_SUCCESS",
  ADD_CLIENT_FAILED: "trainer/ADD_CLIENT_FAILED",
  RESET_STATE: "trainer/RESET_STATE"
};
