export const ACCOUNTS_ACTION_TYPES = {
  GET_ACCOUNTS_BALANCE_SUCCESS: 'accounts/GET_ACCOUNTS_BALANCE_SUCCESS',
  GET_ACCOUNTS_BALANCE_FAILED: 'accounts/GET_ACCOUNTS_BALANCE_FAILED',
  GET_ACCOUNT_BALANCE_SUCCESS: 'accounts/GET_ACCOUNT_BALANCE_SUCCESS',
  GET_ACCOUNT_BALANCE_FAILED: 'accounts/GET_ACCOUNT_BALANCE_FAILED',
  DELETE_ACCOUNT_SUCCESS: 'accounts/DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAILED: 'accounts/DELETE_ACCOUNT_FAILED',
  RESET_STATE: 'accounts/RESET_STATE'
};
