export const TRANSACTIONS_ACTION_TYPES = {
  GET_TRANSACTIONS_SUCCESS: 'transactions/GET_TRANSACTIONS_SUCCESS',
  GET_TRANSACTIONS_FAILED: 'transactions/GET_TRANSACTIONS_FAILED',
  GET_RECENTBILLS_SUCCESS: 'transactions/GET_RECENTBILLS_SUCCESS',
  GET_RECENTBILLS_FAILED: 'transactions/GET_RECENTBILLS_FAILED',
  GET_RECURRING_TRANSACTIONS_SUCCESS:
    'transactions/GET_RECURRING_TRANSACTIONS_SUCCESS',
  GET_RECURRING_TRANSACTIONS_FAILED:
    'transactions/GET_RECURRING_TRANSACTIONS_FAILED',
  GET_ACCOUNT_TRANSACTIONS_SUCCESS:
    'transactions/GET_ACCOUNT_TRANSACTIONS_SUCCESS',
  GET_ACCOUNT_TRANSACTIONS_FAILED:
    'transactions/GET_ACCOUNT_TRANSACTIONS_FAILED',
  SYNCING: 'transactions/SYNCING',
  RESET_STATE: 'transactions/RESET_STATE'
};
