export const CLIENT_ACTION_TYPES = {
  GET_CLIENTS_SUCCESS: "client/GET_CLIENTS_SUCCESS",
  GET_CLIENTS_FAILED: "client/GET_CLIENTS_FAILED",
  GET_CLIENTSLASTVISITED_SUCCESS: "client/GET_CLIENTSLASTVISITED_SUCCESS",
  GET_CLIENTSLASTVISITED_FAILED: "client/GET_CLIENTSLASTVISITED_FAILED",
  ADD_CLIENT_SUCCESS: "client/ADD_CLIENT_SUCCESS",
  ADD_CLIENT_FAILED: "client/ADD_CLIENT_FAILED",
  RESET_STATE: "client/RESET_STATE"
};
