export const FREQUENCIES_ACTION_TYPES = {
  GET_FREQUENCIES_SUCCESS: 'frequencies/GET_FREQUENCIES_SUCCESS',
  GET_FREQUENCIES_FAILED: 'frequencies/GET_FREQUENCIES_FAILED',
  REFRESH_FREQUENCIES_SUCCESS: 'frequencies/REFRESH_FREQUENCIES_SUCCESS',
  REFRESH_FREQUENCIES_FAILED: 'frequencies/REFRESH_FREQUENCIES_FAILED',
  ADD_FREQUENCIES_SUCCESS: 'frequencies/ADD_FREQUENCIES_SUCCESS',
  ADD_FREQUENCIES_FAILED: 'frequencies/ADD_FREQUENCIES_FAILED'
};
