export const CATEGORIES_ACTION_TYPES = {
  GET_CATEGORIES_SUCCESS: 'categories/GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILED: 'categories/GET_CATEGORIES_FAILED',
  REFRESH_CATEGORIES_SUCCESS: 'categories/REFRESH_CATEGORIES_SUCCESS',
  REFRESH_CATEGORIES_FAILED: 'categories/REFRESH_CATEGORIES_FAILED',
  ADD_CATEGORIES_SUCCESS: 'categories/ADD_CATEGORIES_SUCCESS',
  ADD_CATEGORIES_FAILED: 'categories/ADD_CATEGORIES_FAILED'
};
